FROM openjdk:17
WORKDIR /home/wiremock
RUN apt-get update && apt-get install -y wget
RUN wget https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/3.3.1/wiremock-standalone-3.3.1.jar -O wiremock.jar
COPY mappings /home/wiremock/mappings
COPY __files /home/wiremock/__files
EXPOSE 8081
CMD ["java", "-jar", "wiremock.jar", "--port", "8081"]